[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
axum-macros = "0.5.0"
bytes = "1.10.1"
http-body = "1.0.1"
log = "0.4.27"
rusqlite = "0.35.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.45.0", features = ["full", "macros", "rt-multi-thread"] }
tower-http = { version = "0.6.4", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
utoipa = { version = "5.3.1", features = ["yaml"] }
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }
uuid = { version = "1.16.0", features = ["v4"] }
