[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
axum-macros = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
surrealdb = { version = "2.3.1", features = ["kv-mem"] }
tokio = { version = "1.45.0", features = ["full", "macros", "rt-multi-thread"] }
utoipa = { version = "5.3.1", features = ["yaml"] }
utoipa-swagger-ui = { version = "9.0.1", features = ["axum"] }
