openapi: 3.1.0
info:
  title: Simple Prompt Storage API
  description: |-
    Simple prompt storage API that enables users to store and retrieve prompts, no longer requiring new deployments for
            prompt updates.
  license:
    name: ''
  version: 0.0.1
paths:
  /:
    get:
      tags: []
      summary: Get hello world message
      operationId: hello_world
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
  /prompt:
    get:
      tags: []
      summary: Get prompt
      operationId: prompt
      responses:
        '200':
          description: Successly retrieved prompt
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Prompt not found
        '500':
          description: Internal server error
components: {}
