openapi: 3.1.0
info:
  title: Simple Prompt Storage API
  description: |-
    Simple prompt storage API that enables users to store and retrieve prompts, no longer requiring new deployments for
            prompt updates.
  license:
    name: ''
  version: 0.0.1
paths:
  /prompt:
    post:
      tags: []
      summary: Create prompt
      operationId: create_prompt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptWithoutId'
        required: true
      responses:
        '201':
          description: Successfully created prompt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prompt'
        '400':
          description: Invalid request body
  /prompt/{id}:
    get:
      tags: []
      summary: Get prompt
      operationId: get_prompt
      parameters:
      - name: id
        in: path
        description: Prompt identifier
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successly retrieved prompt
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Prompt not found
        '500':
          description: Internal server error
    put:
      tags: []
      summary: Update prompt
      operationId: update_prompt
      responses:
        '200':
          description: Successly updated prompt
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Invalid request body
        '404':
          description: Prompt not found
    delete:
      tags: []
      summary: Delete prompt
      operationId: delete_prompt
      responses:
        '200':
          description: Successly deleted prompt
        '404':
          description: Prompt does not exist
        '500':
          description: Internal server error
components:
  schemas:
    Prompt:
      type: object
      required:
      - id
      - content
      properties:
        content:
          type: string
        id:
          type: string
    PromptMetadata:
      type: object
      required:
      - name
      - description
      properties:
        description:
          type: string
        name:
          type: string
    PromptWithoutId:
      type: object
      required:
      - metadata
      - content
      properties:
        content:
          type: string
        metadata:
          $ref: '#/components/schemas/PromptMetadata'
